spring:
  datasource:
    url: jdbc:oracle:thin:@(description =(load_balance= off)(failover = on)(connect_timeout=1)(retry_count=3)(address_list =(address = (protocol = tcp)(host = 134.80.223.19)(port = 8081))(address = (protocol = tcp)(host =  134.80.223.19)(port = 8082))(address = (protocol = tcp)(host =  134.80.223.19)(port = 8083)))(connect_data =(service_name = pdbsurvey)))
    username: survey
    password: ksDJ_I342
    driver-class-name: oracle.jdbc.OracleDriver
    initial-size: 5
    min-idle: 5
    max-idle: 10
    max-wait: 10000